= CookieCutter variables reference
:toc:

== How to read the variables definition

In link:cookiecutter.json[] we define all the variables used in the project.

[id=hidden_variables]
If the value starts with `_`::
it is not shown to the user.

If the value is an array::
It limits the the value to one of the choices in the array. +
The first item in the array is used as the default choice.

If the value is just a string::
It is the default value. The user can change it to any input.

[id=values_based_on_previous_values]
== Values based on previous values

Values in cookiecutter.json are rendered using jinja2 templates. This means that you can use previous values in the definition of the next one.

For example:
[source,json]
----
{
    "project_title": "My Project",
    "repo_name": "{{ cookiecutter.project_title | slugify }}",
}
----

== Adding new variables

When adding new variables to the project template `cookiecutter.json` make sure to also add them to  `CookiecutterVariables.adoc` file.

Wrap them in a `_ tag::my_cool_variable[]` blocks, so you can automatically include the variable definition in the reference documentation. +
This allows to show the default value thh documentation without having to hard-code it there.


TIP: Don't be afraid to add new variables, even if you're using an existing variable in the project, just <<values_based_on_previous_values, define a new variable based on the same value>> with a <<hidden_variables, _ prefix>> and use it. This will allow future developers to extend the logic based on that value that use much easier.

[id=variables]
== CookieCutter variables

[id=project_title]
=== project_title

Public title of the project. +
This is used in docs, emails navbars, etc. Anywhere the project name is shown to the public this is used.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=project_title]
}
----

[id=repo_name]
=== repo_name

TIP: If you're using `repo_name` or `project_title` in a new place in the projects where you're using it as a string and have the ability to import django.conf.settings, import the value from there instead of using this variable, so the code is the same for all generated projects.

Preferably lowercase codename, used for the directory structure and Python modules.

Used as the root for a lot of things. Including folder names and the core project name on servers.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=repo_name]
}
----

[id=thorgate]
=== thorgate

Are you from thorgate? Exclude common config present for Thorgate.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=thorgate]
}
----

[id=live_domain_name]
=== live_domain_name

Production domain name of the site (e.g. example.com). NOTE: should be lowercase and valid FQDN.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=live_domain_name]
}
----


[id=test_host]
=== test_host

Hostname for test server. Used to generate the first ansible host.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=test_host]
}
----

[id=admin_email]
=== admin_email

Project email. Used for any data requiring email, django admin and certbot expiration notifications.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=admin_email]
}
----


[id=include_celery]
=== include_celery

Include Celery with Redis as the broker.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=include_celery]
}
----

[id=include_wagtail]
=== include_wagtail

Include wagtail, using the latest version.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=include_wagtail]
}
----


[id=docker_base_image]
=== docker_base_image

Base Docker images to use.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=docker_base_image]
}
----

[id=python_version]
=== python_version

Python version to use.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=python_version]
}
----

[id=node_version]
=== node_version

Node.js version to use.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=node_version]
}
----

[id=postgres_version]
=== postgres_version

Postgres version to use.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=postgres_version]
}
----

[id=django_admin_path]
=== django_admin_path


Django Admin panel URL path.
*NOTE:* Should not start or end with `/`.

Defaults to `adminpanel`.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=django_admin_path]
}
----

[id=django_health_check_path]
=== django_health_check_path

Django health check URL path.
*NOTE:* Should not start or end with `/`.

Defaults to `_health`.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=django_health_check_path]
}
----

[id=django_folder_name]
=== django_folder_name


Directory name for the Django codebase.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=django_folder_name]
}
----

[id=default_django_app]
=== default_django_app


Name of the core Django app for the project

.definition
[source,json]
----
{
include::cookiecutter.json[tags=default_django_app]
}
----

[id=django_media_engine]
=== django_media_engine


Django remote media storage engine to use.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=django_media_engine]
}
----

[id=gitlab_repo_url]
=== gitlab_repo_url



*[Optional]* Gitlab repo url in format: https://gitlab.com/your-group/project-name.

This is used for deriving the Gitlab repository url to use when deploying or the default
Docker registry url used for the project. Additionally the CI badges in the README file
are created based on this value.

NOTE:  If this is not defined during the project creation/upgrade then one needs to manually update the
 repository variable inside `ansible/group_vars/all/vars.yml` file of the resulting project to the correct
 git repository url (SSH). Additionally, when `build_in_ci` is set to `yes` then the image urls in `environemnt`
 file need to be updated to correct values too.

WARNING: If you're using a nested group, then you should use the git@ format for the repo url. see link:https://gitlab.com/thorgate-public/django-project-template/-/blob/master/tests/test_filters.py#L86-L101[this test case].

.definition
[source,json]
----
{
include::cookiecutter.json[tags=gitlab_repo_url]
}
----

[id=frontend_style]
=== frontend_style

Set the type of frontend to use.

.definition
[source,json]
----
{
include::cookiecutter.json[tags=frontend_style]
}
----


[id=webapp_include_storybook]
=== webapp_include_storybook

Webapp only: Include storybook configuration?

.definition
[source,json]
----
{
include::cookiecutter.json[tags=webapp_include_storybook]
}
----



[id=x_frame_options]
=== x_frame_options

Note::  This variable affects Content Security Policy (CSP) (https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)
settings.

Set X-Frame-Options header for nginx config.

You should choose `SAMEORIGIN` when you want to display current page in a frame on another page, but only within the
current domain.


.definition
[source,json]
----
{
include::cookiecutter.json[tags=x_frame_options]
}
----


[id=use_mypy]
=== use_mypy

Use MyPy static types checker?

.definition
[source,json]
----
{
include::cookiecutter.json[tags=use_mypy]
}
----

[id=use_cypress]
=== use_cypress

Use Cypress autotests?

.definition
[source,json]
----
{
include::cookiecutter.json[tags=use_cypress]
}
----

[id=build_in_ci]
=== build_in_ci

.definition

Do you want to build docker images in CI for deployment?

NOTE: Requires a docker registry.

[source,json]
----
{
include::cookiecutter.json[tags=build_in_ci]
}
----

[id=use_auto_deploy]
=== use_auto_deploy

Do you want to use automatic deployments?

.definition
[source,json]
----
{
include::cookiecutter.json[tags=use_auto_deploy]
}
----
