= CookieCutter variables reference
:toc:

project_title::

Public title of the project. +
This is used in docs, emails navbars, etc. Anywhere the project name is shown to the public this is used.

repo_name::

Preferably lowercase codename, used for the directory structure and Python modules.

Used as the root for a lot of things. Including folder names and the core project name on servers.

Default value is `project_title` slugified.

thorgate::

Are you from thorgate? Exclude common config present for Thorgate.

Choice variable. Valid variables: `yes`, `no`. Defaults to `yes`.

live_domain_name::

Production domain name of the site (e.g. example.com). NOTE: should be lowercase and valid FQDN.

Defaults to `&quot;{{ cookiecutter.repo_name | as_hostname }}.com&quot;`.

test_host::

Hostname for test server. Used to generate the first ansible host.

Defaults to `test.{{cookiecutter.live_domain_name}}` or `{{cookiecutter._tg_recommended_test_server}}` if `is_thorgate`

admin_email::

Project email. Used for any data requiring email, django admin and certbot expiration notifications.

Defaults to `info@{{cookiecutter.live_domain_name}}` or `{{cookiecutter._tg_webmaster_email}}` if `is_thorgate`

include_celery::

Include Celery with Redis as the broker.

Choice variable. Valid variables: `yes`, `no`. Defaults to `no`.

docker_base_image::

Base Docker images to use.

Choice variable. Valid variables: `alpine`, `debian`. Defaults to `alpine`.

python_version::

Python version to use.

node_version::

Node.js version to use.

postgres_version::

Postgres version to use.

django_admin_path::

Django Admin panel URL path.
*NOTE:* Should not start or end with `/`.

Defaults to `adminpanel`.

django_health_check_path::

Django health check URL path.
*NOTE:* Should not start or end with `/`.

Defaults to `_health`.

django_folder_name::

Directory name for the Django codebase.

Defaults to `{{ cookiecutter.repo_name }}`, other options are `backend` or `django`.

default_django_app::

Name of the core Django app for the project

Defaults to `{{ cookiecutter.repo_name }}`, other options are `backend` or `core`.

django_media_engine::

Django remote media storage engine to use.

Choice variable. Valid variables: `S3`, `GCS`. Defaults to `S3`.

gitlab_repo_url::

*[Optional]* Gitlab repo url in format: https://gitlab.com/your-group/project-name.

This is used for deriving the Gitlab repository url to use when deploying or the default
Docker registry url used for the project. Additionally the CI badges in the README file
are created based on this value.

Defaults to `git@gitlab.com/{% if cookiecutter.thorgate == 'yes' %}thorgate{% else %}your-group{% endif %}/{{cookiecutter.repo_name}}.git`.

NOTE:  If this is not defined during the project creation/upgrade then one needs to manually update the
 repository variable inside `ansible/group_vars/all/vars.yml` file of the resulting project to the correct
 git repository url (SSH). Additionally, when `build_in_ci` is set to `yes` then the image urls in `environemnt`
 file need to be updated to correct values too.

frontend_style::

Set the type of frontend to use.

Choice variable. Valid variables: `webapp`, `spa`. Defaults to `webapp`.

webapp_include_storybook::

Webapp only: Include storybook configuration?

Choice variable. Valid variables: `yes`, `no`. Defaults to `no`.

use_mypy::

Use MyPy static types checker?

Choice variable. Valid variables: `yes`, `no`. Defaults to `no`.

use_cypress::

Use Cypress autotests?

Choice variable. Valid variables: `yes`, `no`. Defaults to `no`.

build_in_ci::

Do you want to build docker images in CI for deployment?
*NOTE:* Requires a docker registry.

Choice variable. Valid variables: `yes`, `no`. Defaults to `no`.

use_auto_deploy::

Do you want to use automatic deployments?

Choice variable. Valid variables: `yes`, `no`. Defaults to `no`.
