[tool.poetry]
name = "{{ cookiecutter.repo_name }}-ansible"
version = "1.0.0"
description = "Ansible scripts for {{ cookiecutter.project_title }} deployment"
authors = ["Thorgate <hi@thorgate.eu>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
ansible = "^10.0"
yq = "^2.14.0"
jq = "^1.2.2"

[tool.poetry.dev-dependencies]
pyyaml = "^6"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
