[project]
name = "{{ cookiecutter.repo_name }}-ansible"
version = "1.0.0"
description = "Ansible scripts for {{ cookiecutter.project_title }} deployment"
authors = [
    {name = "Thorgate", email = "hi@thorgate.eu"}
]
readme = "README.adoc"
requires-python = ">=3.10,<4.0"
dependencies = [
    "ansible (>=10.0,<11.0)",
    "tg-bw-helper (>=1.0.0,<2.0.0)",
    "yq (>=2.14.0,<3.0.0)",
    "jq (>=1.2.2,<2.0.0)",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

