FROM docker:latest

RUN apk update && \
    apk upgrade && \
    apk add python3 python3-dev build-base libffi-dev openssl-dev git bash rust cargo && \
    apk add yq --repository http://dl-3.alpinelinux.org/alpine/edge/community/
RUN python3 -m ensurepip

ENV POETRY_HOME "$HOME/.poetry"
ENV POETRY_NO_INTERACTION 1

RUN wget -O - -o /dev/null https://install.python-poetry.org | python3 -
ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"
