FROM docker:latest

RUN apk update && \
    apk upgrade && \
    apk add python3 python3-dev build-base libffi-dev openssl-dev git bash && \
    apk add yq --repository http://dl-3.alpinelinux.org/alpine/edge/community/
RUN python3 -m ensurepip
RUN pip3 install docker-compose
