# Generated by Django 4.2.11 on 2024-03-22 14:00

from django.contrib.postgres.operations import CreateCollation
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_id"),
    ]

    operations = [
        CreateCollation(
            "case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        ),
        # This migration is being modified, since it fails to keep working in modern combination
        # of Django & Postgres, due to Django creating indexes over this field and postgres being
        # unable to make an index over non-deterministic collation.
        # Next migration, 0006_alter_user_email_user_unique_lower_email, handles removing the
        # collation if it was added by previous version of this migration
    ]
