# Generated by Django 4.0.10 on 2023-04-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.RenameField(
            model_name="user",
            old_name="date_joined",
            new_name="created",
        ),
        migrations.AddField(
            model_name="user",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Updated timestamp"
            ),
        ),
    ]
