# Generated by Django 5.2.11 on 2026-02-12 10:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_options_rename_date_joined_user_created_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email address"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                models.OrderBy(django.db.models.functions.text.Lower("name"), descending=True),
                name="unique_lower_email",
            ),
        ),
    ]
