==== Server setup

Your server needs to have https://docs.docker.com/engine/installation/[Docker Engine] as well as https://docs.docker.com/compose/[Docker Compose] installed.

We also assume that you have Nginx and Postgres running in Docker containers and reachable via
'private' network. We also make a few assumptions regards directories that will be used as volumes for static assets,
etc. You can find these paths in link:../docker-compose.production.yml[docker-compose.production.yml].

{%- if cookiecutter.build_in_ci == YES %}

===== Enable registry access for server

This project is deployed with docker images. The images themselves are built in Gitlab CI. To
be able to deploy the code to the cloud the target server must be able to pull images from registry.gitlab.com.

. Navigate to the Settings ->  Repository  ->  Deploy tokens of the project in gitlab
** {{ cookiecutter.gitlab_repo_url }}/-/settings/repository/#js-deploy-tokens
. Add a deploy token if it does not exist already for the server.
  Set the name to server name and use the project name for username.
  Under permissions make sure to only enable `read_registry`.
. Add the deploy token value to the host specific vault file under `registry_token` variable.
. Now you can run the ansible stack to set up the docker authentication

NOTE:  If `docker login` times out then check if your server has `golang-docker-credential-helpers` installed.
 This helper requires X-Server configuration but this fails when it is not installed (which is usually the case within servers).
 If the helper is installed then either remove it or configure a headless helper instead. You can remove it with the following command:
 `
      dpkg -r --ignore-depends=golang-docker-credential-helpers golang-docker-credential-helpers
`

*Note:* When you are working directly in the server run the following command to be able to pull images
 from the docker registry:

[source,bash]
----
source /srv/{{ cookiecutter.repo_name }}/registry.sh
----

The script sets the value of DOCKER_CONFIG to a project specific directory to allow using multiple
credentials for the same docker registry host. This is a workaround for the following
https://github.com/moby/moby/issues/37569[issue in docker].

{%- endif %}

===== The first deployment checklist

* Figure out which server you're going to deploy to.
 We usually have one main test server and one main production server for new project.
* Check link:./inventory[inventory] file. It has two groups - `test` and `live`.
 Ensure that the server you'll use is added to the correct group.
* Add (or update) the `vars.yml` and `vault.yml` files for the server in the link:./host_vars[host_vars] directory.
* When creating the files use link:./host_vars/vars-template.yml[vars-template.yml] and
 link:./host_vars/vault-template.yml[vault-template.yml] as an example.
* If you created the vault file make sure to encrypt it: `ansible-vault encrypt host_vars/<hostname>/vault.yml`
* NB: Vault for production and test should have different password.
* Check django settings (`settings/cloud.py`)
* Add the server's SSH key (`/root/.ssh/id_rsa.pub`) to the project repo settings as deployment key.
* Ensure you've committed and pushed all relevant changes.

{% if cookiecutter.django_media_engine == S3 -%}
{% if cookiecutter.thorgate == YES %}

====== AWS setup

* Ensure you have sufficient permissions in AWS to create a bucket and assume to terraform role (see manual steps below if not using terraform)
* Look over the terraform definitions
 * ./deploy/terraform/variables.tf Make sure that the region is the closest one to the user of the project.
 * ./deploy/terraform/modules/s3_media
 - Public access is denied by default, if you want it to be possible to access without signed urls, change these settings.
* Set your aws credentials
 * `export AWS_ACCESS_KEY_ID=...`
 * `export AWS_SECRET_ACCESS_KEY=...`
* run `make setup-terraform workspace=WORKSPACE` where WORKSPACE is 'staging', 'production'
* Keep the terminal window open as some of these values should be copied into the ansible variables (secrets belong in the vault).

{% endif %}

====== GCS setup

{% endif %}{% if cookiecutter.django_media_engine == GCS -%}
1. Create a service account (https://cloud.google.com/docs/authentication/getting-started[Google Getting Started Guide]).
2. Create the key and download your-project-XXXXX.json file.
3. Make sure your service account has access to the bucket and appropriate permissions. (https://cloud.google.com/storage/docs/access-control/using-iam-permissions[Using IAM Permissions]).
4. Put the contents of the key file into ansible variable `django_gs_credentials` as a json string

{%- endif %}

Now that the prerequisites are done you can deploy the code with the following command.
____

Replace `ENV` with either `test` or `live` (or the actual hostname of the target server).

____

[source,bash]
----
poetry run ansible-playbook --limit ENV deploy.yml
----

If it worked, you're all done, congrats!

Otherwise, if something else broke, you can in most cases fix it and then just run the
Ansible stack again.
