{%- raw -%}
- name: "Ensure local site is turned off"
  shell: "{{ compose_command_local }} down"
  delegate_to: localhost
  vars:
    ansible_become: no


- name: "Delete files in the local postgres data directory"
  shell: >
    {{ compose_command_local }} run --rm postgres bash -c "rm -r /var/lib/postgresql/data/*"
  delegate_to: localhost
  vars:
    ansible_become: no


- name: "Generate an unique filename for dump"
  set_fact:
    dump_filename: "/tmp/mirror-{{ project | mandatory }}-{{ ansible_date_time.epoch }}.pg_dump"


- name: "Create a fresh DB dump on the server"
  shell: >
    docker exec -i postgres-{{ postgres_version | mandatory }} pg_dump -U {{ project }} \
      --format=custom --compress=0 {{ project }} > {{ dump_filename }}
  no_log: true


- name: "Download the dump file"
  synchronize:
    src: "{{ dump_filename }}"
    dest: "{{ dump_filename }}"
    mode: pull
    set_remote_user: no
    recursive: no
  delegate_to: localhost
  vars:
    ansible_become: no


- name: "Turn postgres on again"
  shell: "{{ compose_command_local }} up -d --build postgres"
  delegate_to: localhost
  vars:
    ansible_become: no


- name: "Copy wait for it script into postgres container"
  shell: >
    {{ compose_command_local }} cp ../wait-for-it.sh postgres:/wait-for-it.sh
  delegate_to: localhost
  vars:
    ansible_become: no


- name: "Give postgres some time to start up"
  shell: >
    {{ compose_command_local }} exec -T postgres /wait-for-it.sh 127.0.0.1:5432 -t 60
  delegate_to: localhost
  vars:
    ansible_become: no


- name: "Delete the remote dump file"
  file:
    path: "{{ dump_filename }}"
    state: absent


- name: "Load the dump file locally"
  shell: >
     {{ compose_command_local }} exec -T postgres pg_restore -h 127.0.0.1 -U {{ project }} -d {{ project }} < {{ dump_filename }}
  delegate_to: localhost
  vars:
    ansible_become: no


- name: "Delete the local dump file"
  file:
    path: "{{ dump_filename }}"
    state: absent
  delegate_to: localhost
  vars:
    ansible_become: no


- name: "Turn everything off again"
  shell: "{{ compose_command_local }} down"
  delegate_to: localhost
  vars:
    ansible_become: no
{%- endraw %}
