# Based on Node 10 Alpine image
FROM node:10-alpine

# Install system requirements
RUN apk add --no-cache alpine-sdk python bash

# Install prettier for formatting
# KEEP THIS VERSION IN SYNC WITH THE ONE USED IN PACKAGE
RUN yarn global add "prettier@1.18.2"

# Set the default directory where CMD will execute
WORKDIR /app
VOLUME /app

CMD yarn check-formatting
